### ISSUE TITLE
Prediction NotImplementedError

### ISSUE THREAD

**Issue by matusdrobuliak66** [hrenski/custom-model-sagemaker#1]
While `y_hat_train = predictor.predict(X_t)` is working, the test prediction: `y_hat_test = predictor.predict(X_test)` gives back error with statement: 

Traceback (most recent call last):  File "/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_functions.py", line 93, in wrapper    return fn(*args, **kwargs)  File "/opt/ml/code/model_logic.py", line 87, in predict_fn    return model.predict(input_object)  File "/miniconda3/lib/python3.7/site-packages/gam_model/_models.py", line 38, in predict    exog_smooth = X  File "/miniconda3/lib/python3.7/site-packages/statsmodels/gam/generalized_additive_model.py", line 217, in predict    transform=transform)  File "/miniconda3/lib/python3.7/site-packages/statsmodels/gam/generalized_additive_model.py", line 182, in _tranform_predict_exog    ex_smooth = self.model.smoother.transform(exog_smooth)  File "/miniconda3/lib/python3.7/site-packages/statsmodels/gam/smooth_basis.py", line 798, in transform    for i in range(self.k_variables)))  File "/miniconda3/lib/python3.7/site-packages/statsmodels/gam/smooth_basis.py", line 798, in <genexpr>    for i in range(self.k_variables)))  File "/miniconda3/lib/python3.7/site-packages/statsmodels/gam/smooth_basis.py", line 495, in transform    include_intercept=self.include_intercept)  File "/miniconda3/lib/python3.7/site-packages/statsmodels/gam/smooth_basis.py", line 65, in _eval_bspline_basis    

raise **NotImplementedError: some data points fall outside the outermost knots, and I'm not sure how to handle them. (Patches accepted!)**

**Comment by hrenski** [comment]
Thanks for giving the code a try and for the feedback!

From the error message, it looks like there are samples in your testing dataset fall outside the range of coverage in the training dataset; in other words (using your code), X_t.max() < X_test.max() or X_t.min() > X_test.min(). The splines that the underlying package, statsmodel, is using aren't currently designed to handle extrapolating beyond the outermost knots (aka the boundaries of the data).

For production code, we'd definitely want to deal with this more robustly, but for this example, you can always drop those points in the testing dataset that fall outside the training data's range. When I have a bit of time, I'll add that check in.

**Comment by hrenski** [comment]
So it took me a little while to circle back to this, but I've added a check in the notebook to remove entries beyond the extremum of the training data. 

Thanks again!
